template = ""
rev_id = 333
template_sha = "c0f15a905d69cb451762275644bf5c3133bfc106"

[replacements]
__GLOTTOLOG_ID__ = "temb1276"
__LICENSE__ = "GPLv3"
__REPO__ = "lang-tqb"
__UND2C__ = "tqb"
__UNDEFINED__ = "Tembé"
__UND__ = "tqb"
