template = ""
rev_id = 316
template_sha = "4ab8b281df40078b127cd15db6e63507b51b4424"

[replacements]
__GLOTTOLOG_ID__ = "temb1276"
__LICENSE__ = "GPLv3"
__REPO__ = "lang-tqb"
__UND2C__ = "tqb"
__UNDEFINED__ = "Tembé"
__UND__ = "tqb"
